name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test
      run:
        echo ${{secrets.ALI_DOCKER_HUB_REGISTRY}}  ${{secrets.ALI_DOCKER_HUB_USN}} ${{secrets.ALI_DOCKER_HUB_PWD}}

   # - name: Save state
   #   run: echo "::save-state name={name}::{value}"

   # - name: Save state
   #   run: echo "{name}={value}" >> $GITHUB_STATE

   # - name: Set environment variable
   #   run: echo "MY_ENV_VAR=myValue" >> $GITHUB_ENV

   # - name: Use environment variable
   #   run: |
   #       echo "The value of MY_ENV_VAR is $MY_ENV_VAR"



    - name: Get current date
      id: date
      run: echo "today=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV
   #   run: echo "::set-output name=today::$(date +'%Y_%m_%d_%H_%M')"        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{secrets.ALI_DOCKER_HUB_REGISTRY}}
        username: ${{secrets.ALI_DOCKER_HUB_USN}}
        password: ${{secrets.ALI_DOCKER_HUB_PWD}} 

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags:  |
          ${{secrets.ALI_DOCKER_HUB_REGISTRY}}/zhuang/downbydocker:latest
          ${{secrets.ALI_DOCKER_HUB_REGISTRY}}/zhuang/downbydocker:$today
          # ${{ steps.date.outputs.today }}
