name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: 
        tag=$(date +%s)
        echo ${{ secrets.ALI_DOCKER_HUB_USN }} 
        docker build . --file Dockerfile --tag downbydocker:${{tag}}
        docker login -u ${{ secrets.ALI_DOCKER_HUB_USN }} -p ${{ secrets.ALI_DOCKER_HUB_PWD }} ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
        docker tag downbydocker:tag ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/zhuang/downbydocker:${{tag}}
        docker push ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/zhuang/downbydocker:${{tag}}
