name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test
      run:
        echo ${{secrets.ALI_DOCKER_HUB_REGISTRY}}  ${{secrets.ALI_DOCKER_HUB_USN}} ${{secrets.ALI_DOCKER_HUB_PWD}}

   # - name: Save state
   #   run: echo "::save-state name={name}::{value}"

   # - name: Save state
   #   run: echo "{name}={value}" >> $GITHUB_STATE

   # - name: Set environment variable
   #   run: echo "MY_ENV_VAR=myValue" >> $GITHUB_ENV

   # - name: Use environment variable
   #   run: |
   #       echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
#
# - name: Store build timestamp
  #  run: echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV

 # - name: Deploy using stored timestamp
#    run: echo "Deploying at $BUILD_TIME"

    - name: Get current date
      id: date
    #  run: echo "BUILD_TIME=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV
      run: echo "::set-output name=today::$(date +'%Y_%m_%d_%H_%M')" 

    - name: Deploy using stored timestamp
      run: echo "Deploying at $BUILD_TIME"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{secrets.ALI_DOCKER_HUB_REGISTRY}}
        username: ${{secrets.ALI_DOCKER_HUB_USN}}
        password: ${{secrets.ALI_DOCKER_HUB_PWD}} 

    - name: Set color
      id: color-selector
      run: echo "SELECTED_COLOR=green" >> "$GITHUB_ENV"
    - name: Get color
      env:
        SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
      run: echo "The selected color is $SELECTED_COLOR"

    - name: sync image
      env:
        SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
      run: docker pull apache/rocketmq:4.9.4 && docker tag apache/rocketmq:4.9.4 ${{secrets.ALI_DOCKER_HUB_REGISTRY}}/zhuang/apache/rocketmq:4.9.4 && docker push ${{secrets.ALI_DOCKER_HUB_REGISTRY}}/zhuang/apache_rocketmq:4.9.4


    - name: Build and push
      uses: docker/build-push-action@v6 
      with:
        context: .
        push: true
        tags:  |
          ${{secrets.ALI_DOCKER_HUB_REGISTRY}}/zhuang/downbydocker:latest
          ${{secrets.ALI_DOCKER_HUB_REGISTRY}}/zhuang/downbydocker:${{ steps.date.outputs.today }}
          ${{secrets.ALI_DOCKER_HUB_REGISTRY}}/zhuang/downbydocker:${{ env.SELECTED_COLOR }}
